name: Check pushed

on:
  # push:
  #   branches: [ master ]
  pull_request:
    types: [ opened, edited ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: ./mvnw clean verify