name: Publish on tag push

on:
  push:
    branches: [ master ]
    tags: 
      - '*'

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Get tags
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: ./mvnw clean verify

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_REPO }}/tesk-api:latest, ${{ secrets.DOCKERHUB_REPO }}/tesk-api:${{ steps.get_tag.outputs.tag }}
    
    
